############################################################################
# 운영 환경에 따른 프로파일 별 환경 설정 그룹화
############################################################################
spring:
  profiles:
    active: dev
    group:
      local: local, common
      dev: dev, common