#################################################################################
# 로컬 환경 설정
#################################################################################
spring:
  config:
    activate:
      on-profile:
        - local
  # MariaDB 데이터베이스 연결 정보
  datasource:
    url: jdbc:mariadb://localhost:3306/prec?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: suihin92
    password: tq847
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    root: WARN
    web: INFO

server:
  port: 8082