#################################################################################
# 개발 환경 설정
#################################################################################
spring:
  config:
    activate:
      on-profile:
        - dev
  # H2 인메모리 데이터베이스 연결 정보
  datasource:
    url: jdbc:h2:mem:prec;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver
  # 데이터베이스 스키마 버전 관리 비활성화
  flyway:
    enabled: false
  # SQL 초기 데이터 설정
  sql:
    init:
      # ALWAYS : 애플리케이션 실행 때마다 SQL스크립트 실행, EMBEDDED : 내장 데이터베이스 사용시 SQL스크립트 실행, NEVER : SQL스크립트 실행X
      mode: EMBEDDED
      schema-locations:
        - classpath:h2/scripts/schema.sql
  # H2 콘솔에 접속하기 위한 설정 정보
  h2:
    console:
      path: /h2-console   # H2 콘솔 경로
      enabled: true       # H2 콘솔 사용

logging:
  level:
    root: INFO
    web: DEBUG

# 내장 톰캣 서버의 포트 설정
server:
  port: 80
