-- 사용자 계정 테이블
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID                      INT                         GENERATED BY DEFAULT AS IDENTITY,   -- 사용자 번호
    EMAIL                   VARCHAR(40)                 NOT NULL,                           -- 이메일
    PASSWORD                VARCHAR(255)                NOT NULL,                           -- 비밀번호
    NAME                    VARCHAR(15)                 NOT NULL,                           -- 이름
    PHONE                   VARCHAR(11)                 NOT NULL,                           -- 휴대폰 번호
    ACCOUNT_TYPE            VARCHAR(5)                  NOT NULL,                           -- 계정 유형 (일반 / 소셜)
    ENABLED                 TINYINT(1)                  NOT NULL,                           -- 계정 활성화
    DELETE_YN               CHAR(1)                     NOT NULL DEFAULT 'N',               -- 삭제 여부
    DELETED_AT              DATETIME                    NULL,                               -- 삭제 일자
    CREATED_AT              DATETIME                    NOT NULL DEFAULT NOW(),             -- 가입 일자
    UPDATED_AT              DATETIME                    NOT NULL,                           -- 변경 일자
    PRIMARY KEY (ID)
);


-- 사용자 계정별 권한 테이블
DROP TABLE IF EXISTS USER_ROLES;

CREATE TABLE USER_ROLES (
    USER_ID                 INT                         NOT NULL,                   -- 사용자 번호
    ROLE                    VARCHAR(20)                 NOT NULL,                   -- 권한명 (ROLE_*)
    CREATED_AT              DATETIME                    NOT NULL DEFAULT NOW(),     -- 생성 일자
    UPDATED_AT              DATETIME                    NOT NULL                    -- 변경 일자
);


-- 사용자 계정별 프로필 정보 테이블
DROP TABLE IF EXISTS USER_PROFILES;

CREATE TABLE USER_PROFILES (
    PROFILE_ID              INT                         GENERATED BY DEFAULT AS IDENTITY,   -- 프로필 번호
    USER_ID                 INT                         NOT NULL,                           -- 사용자 번호
    PROFILE_IMG_URL         VARCHAR(255)                NOT NULL DEFAULT 'NONE',            -- 프로필 이미지 경로
    INTRODUCTION            VARCHAR(155)                NOT NULL DEFAULT 'NONE',            -- 소개글
    UNIV                    VARCHAR(45)			        NOT NULL DEFAULT 'NONE',            -- 대학
    CITY                    VARCHAR(15)			        NOT NULL DEFAULT 'NONE',            -- 거주 도시
    CREATED_AT              DATETIME                    NOT NULL DEFAULT NOW(),             -- 프로필 등록 일자
    UPDATED_AT              DATETIME                    NOT NULL,                           -- 프로필 변경 일자
    PRIMARY KEY (PROFILE_ID)
);


-- 로그인 이력 테이블
DROP TABLE IF EXISTS LOGIN_HISTORY;

CREATE TABLE LOGIN_HISTORY (
    HISTORY_ID              INT                         GENERATED BY DEFAULT AS IDENTITY,   -- 로그인 이력 번호
    USER_ID                 INT                         NOT NULL,                           -- 사용자 번호
    CLIENT_ID               VARCHAR(15)                 NOT NULL,                           -- 접속 아이피
    USER_AGENT              VARCHAR(255)                NOT NULL,                           -- 사용자 식별 정보
    LOGIN_DATETIME          DATETIME                    NOT NULL,                           -- 로그인 일자
    PRIMARY KEY (HISTORY_ID)
);